// <auto-generated />
namespace Redack.DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02addconstrainttouseridenticon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02addconstrainttouseridenticon));
        
        string IMigrationMetadata.Id
        {
            get { return "201711200849001_02-add-constraint-to-user-identicon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
